name: service gql ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: login to docker github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: build and push
        run: |
          docker build . --tag ghcr.io/dueit-jasanya-aturuang/dueit-tokyo-revengers-service:1.0
          docker push ghcr.io/dueit-jasanya-aturuang/dueit-tokyo-revengers-service:1.0

      - name: deploy to hosting ssh main branch
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_SSHKEY }}
          script: ${{ secrets.SCRIPT }}